name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: https://gist.github.com/sjdj0147/db4c09887dc376535d1a514bc9402b3b
          TIMEZONE: Asia/Seoul
